baseURL = 'http://arian-d.github.io/blog/'
languageCode = 'en-us'
title = "Arian's blog"
theme = "ananke"

[markup.goldmark.renderer]
  unsafe = true

[Taxonomies]
  category = "categories"
  tag = "tags"

[outputs]
  home = ['html', 'rss']
  section = ['html', 'rss']
  taxonomy = ['html']
  term = ['html']

