baseURL = 'http://example.org/'
languageCode = 'en-us'
title = "Arian's blog"
[module]
  [[module.imports]]
    path = "github.com/adityatelange/hugo-PaperMod"

[markup.goldmark.renderer]
  unsafe = true

[Taxonomies]
  category = "categories"
  tag = "tags"


