#+TITLE: An mediocre pseudo-espresso recipe with the AeroPress
#+DATE: 2024-07-02
#+HUGO_BASE_DIR: ../
#+HUGO_WEIGHT: auto
#+HUGO_TAGS: coffee aeropress food

A real espresso requires an espresso machine, and that's somewhat
inconvenient for an average Joe like me, because
- I can't afford one.
- I'm not willing to spend that much money, if I could afford one.
- If I was willing to buy one and could afford it, I wouldn't wanna
  bring it to the office, since I wouldn't be able to use it at home.


So, what can I do? I'm not willing to pay someone to make it for me at
Starbucks, because it's pricey and has never tasted good (to me). There are some
great [[https://en.wikipedia.org/wiki/Third-wave_coffee][3rd wave]] cafe's near me, but then again, I can't leave the
office 5 times a day to buy a fresh shot and come back.

I'll go over the recipe first, and will then explain my
reasoning. Keep in mind that I'm an absolute novice, so take
everything here with a grain of salt.

* The recipe
1. Grind your coffee fine-ish. \approx450-500 \micro m
2. Boil your water to 80^\circ-90^\circ Celsius
3. Put the AeroPress filter in, lock the filter piece.
4. Pour in the coffee ground.
5. Pour 70-80 milliliters of water.
6. Stir *AND* swirl.
7. Swirl again around 3:30 minutes to remove the foam.
8. Drink it at around the 4:00 minute mark.

* Reasoning
- Grind :: This was a personal choice, but the reason I went with a
  finer ground was more flavor. This is, in a sense, a misuse of this
  product, because almost every tutorial and the manual discourage you
  from pressing too hard with a fine grind, but it seemed to have
  resulted in a better taste (for me). Another thing to note is that I
  haven't calibrated my grinder ([[https://1zpresso.coffee/k-ultra/][k-ultra]]) in a while, so those micron
  figures may not be exact.
- Water :: I just go with 80^\circ for dark roasts, and closer to
  90^\circ for light to medium.
- Filter :: I use the paper filter, but [[https://aeropress.com/blogs/blog/aeropress-metal-filter-vs-paper-filters][according to AeroPress'
  website]], the metal filter is better for this style, since the
  metal lets in more of the oil and will result in a better texture.
- Ratio :: The manual only says go up to the first circle, which is
  not an exact amount. For me 70-80 was around there, and the
  confusing part might be that prior to stirring, the water is not
  level, so it's hard to know how much to pour. Most sources out there
  recommended more than 15g of coffee, but for me 15g was already
  plenty of extraction.
- Stirring :: In the Pourover videos and the AeroPress videos by James
  Hoffmann, he recommends swirl over stirring. I personally /feel/ like
  I'm getting more extraction doing stirring first to spread the
  ground and then swirl, but it could very well be confirmation
  bias.
- Timing :: Once again, this was based on James Hoffmann's AeroPress
  video. Although he shows that the extraction isn't as fast after \approx
  2:00 minutes, I felt a noticeably better taste after 3:30 minutes, which might
  not have to do with extraction.


You might've also noticed I didn't try the inverted method. It's not
because of any scientific evidence or experiments; I'm just too scared
to do that on the same desk that I have my laptop on.
  

* Resources
- [[https://cdn.shopify.com/s/files/1/0601/8783/6659/files/AeroPress_Go_instructions-April_2023-English.pdf?v=1682116759][The AeroPress Go Manual]], which is because I got the "Go" version. I
  checked the other manuals, and they don't seem to have the
  espresso-style. Regardless, this is what I initially started with
  and deviated to get more extraction.
- [[https://www.javapresse.com/blogs/aeropress/can-aeropress-make-espresso][These]] [[https://www.javapresse.com/blogs/aeropress/aeropress-espresso-recipe][two]] blog posts were amazing. The recipe is different than mine,
  but they're very valuable in terms of information.
- [[https://coffeechronicler.com/aeropress-espresso/][This blog post]] mentions a more similar to mine, but uses the
  inverted method and has a shorter wait time (though more than the
  previous website). The most interesting thing mentioned here is the
  pressure is not directly correlated to extraction, which is what
  enables one to actually brew something similar to the espresso with
  the AeroPress.
- [[https://aeropress.com/blogs/blog/aeropress-espresso][The official website]], which has a much higher coffee\to water ratio
  than mine, similar to the other sources, but the water temperature is
  closer.
- Most importantly, [[https://www.youtube.com/channel/UCMb0O2CdPBNi-QqPk5T3gsQ][James Hoffmann]] and [[https://aeromatic.app/recipes/james-hoffmann-espresso-aeropress-recipe][his recipe]]. One distinction to
  note is that his is older than this is older than [[https://youtu.be/jBXm8fCWdo8?si=G8kKbb8tSRq5i2X5&t=130]["Understanding The
  AeroPress"]] (timestamped at the time\to extraction graph), which is
  my most important deviation compared to other techniques.

- I'll have to retry these things once I get the metal filter, but
  I'll keep researching and trying different things. Everyone has
  their own taste, but hearing about new techniques and perspectives
  is always refreshing. It makes wonder if I'd need a comment section
  on this blog... 
